server:
  port: 88

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      routing-key: ${random.int(1000000)}
      default-receive-queue: "auth-user"
      exchange: userExchange
  application:
    name: auth-service
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2


jwt:
  secretKey: 1231231231231231231231231231231231231231231231231231231231231231
  tokenPrefix: 'Bearer '
  tokenExpirationForVerification: 10
  tokenExpirationForLogin: 20
