gateway-service:
  timeout-ms: 3000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000
  defaultReplenishRate: 5
  defaultBurstCapacity: 10
  defaultRequestedTokens: 1

server:
  port: 9092

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus, gateway
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
    gateway:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: gateway-service

jwt:
  secretKey: 1231231231231231231231231231231231231231231231231231231231231231
  tokenPrefix: 'Bearer '
  tokenExpirationForVerification: 10
  tokenExpirationForLogin: 20