version: '3.7'

services:
  mongo:
    image: mongo
    restart: on-failure
    container_name: chat-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - ${GLOBAL_NETWORK:-chat-db}
      - ${GLOBAL_NETWORK:-services}
  mongo-express:
    image: mongo-express
    restart: on-failure
    container_name: chat-db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@mongo:27017/
    networks:
      - ${GLOBAL_NETWORK:-mongodb}