version: '3.8'
services:
  postgresql:
    image: postgres:14.1-alpine
    command: postgres -c 'max_connections=300'
    restart: on-failure
    hostname: localhost
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - ${GLOBAL_NETWORK:-db}

volumes:
  db:
    driver: local