server:
  port: 85

elastic-config:
  connectionUrl: localhost:9200
  connectionTimeoutMs: 5000
  socketTimeoutMs: 30000
  password: password
  username: elastic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  application:
    name: search-service