scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'gateway-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['gateway-service:9092']
  - job_name: 'chat-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['chat-service:91']
  - job_name: 'asset-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'asset-service:89' ]
  - job_name: 'auth-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'auth-service:88' ]
  - job_name: 'kafka-to-elastic-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'kafka-to-elastic-service:83' ]
  - job_name: 'user-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'user-service:83' ]
  - job_name: 'search-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'search-service:85' ]