CREATE TABLE IF NOT EXISTS chat_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255) UNIQUE                     NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP(6)                            NOT NULL DEFAULT CURRENT_DATE,
    updated_at TIMESTAMP(6)                                     DEFAULT NULL,
    CONSTRAINT pk_chat_users PRIMARY KEY (id)
);