INSERT INTO "CHAT_PERMISSIONS" ("ID", "AUTHORITY", "CREATED_AT")
VALUES (1, 'VIEW_USER', CURRENT_DATE);

INSERT INTO "CHAT_ROLES" ("ID", "ROLE", "CREATED_AT")
VALUES (1, 'CHAT_USER', CURRENT_DATE);

INSERT INTO "CHAT_ROLE_PERMISSIONS" ("ID", "ROLE_ID", "PERMISSION_ID")
VALUES (1, 1, 1);