server:
  port: 89

log:
  app-name: asset-service


redis:
  host: http://localhost
  port: 6379


spring:
  main:
    allow-bean-definition-overriding=true:
  application:
    name: asset-service
  data:
    redis:
      repositories:
        enabled: true
  redis:
    port: 6379
    host: localhost

retry-config:
  initialIntervalMs: 1000
  maxIntervalMs: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleepTimeMs: 2000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus, gateway
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
    gateway:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

s3:
  accesskey: asdasdas
  secretkey: asdasdas
  region: us-west-2